/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PerlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/epic/perl/parser/antlr/internal/InternalPerl.tokens");
	}
}
