sudo: false

language: java

jdk:
  - oraclejdk8

os:
  - linux

cache:
  directories:
  - $HOME/.m2

env: DISPLAY=:99.0

install: true

before_install:
 - echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
 - echo $JAVA_HOME

before_script:
 - sh -e ./before_script.sh

