/**
 * generated by Xtext 2.9.1
 */
package org.epic.perl.ui.contentassist;

import org.epic.perl.ui.contentassist.AbstractPerlProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PerlProposalProvider extends AbstractPerlProposalProvider {
}
