/*
 * generated by Xtext 2.9.1
 */
package org.epic.perl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.epic.perl.ui.internal.PerlActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PerlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PerlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PerlActivator.getInstance().getInjector(PerlActivator.ORG_EPIC_PERL_PERL);
	}
	
}
