/*
 * generated by Xtext 2.9.1
 */
package org.epic.perl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PerlStandaloneSetup extends PerlStandaloneSetupGenerated {

	def static void doSetup() {
		new PerlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
