/**
 * generated by Xtext 2.9.1
 */
package org.epic.perl;

import org.epic.perl.PerlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PerlStandaloneSetup extends PerlStandaloneSetupGenerated {
  public static void doSetup() {
    PerlStandaloneSetup _perlStandaloneSetup = new PerlStandaloneSetup();
    _perlStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
