/*
 * generated by Xtext 2.9.1
 */
package org.epic.perl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.epic.perl.ui.internal.PerlActivator;

public class PerlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PerlActivator.getInstance().getInjector("org.epic.perl.Perl");
	}

}
