/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Backtick Quote Like Token</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.epic.perl.perl.PerlPackage#getBacktickQuoteLikeToken()
 * @model
 * @generated
 */
public interface BacktickQuoteLikeToken extends QuoteLikeToken
{
} // BacktickQuoteLikeToken
