/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.epic.perl.perl.PerlPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
} // Element
