/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Null Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.epic.perl.perl.PerlPackage#getNullLiteral()
 * @model
 * @generated
 */
public interface NullLiteral extends Expression
{
} // NullLiteral
