/**
 * generated by Xtext 2.9.1
 */
package org.epic.perl.perl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PBlock Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.epic.perl.perl.PBlockExpression#getExpressions <em>Expressions</em>}</li>
 * </ul>
 *
 * @see org.epic.perl.perl.PerlPackage#getPBlockExpression()
 * @model
 * @generated
 */
public interface PBlockExpression extends PExpression
{
  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link org.epic.perl.perl.PExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see org.epic.perl.perl.PerlPackage#getPBlockExpression_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<PExpression> getExpressions();

} // PBlockExpression
