/**
 * generated by Xtext 2.9.1
 */
package org.epic.perl.perl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PFeature Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.epic.perl.perl.PFeatureCall#getFeature <em>Feature</em>}</li>
 *   <li>{@link org.epic.perl.perl.PFeatureCall#getFeatureCallArguments <em>Feature Call Arguments</em>}</li>
 * </ul>
 *
 * @see org.epic.perl.perl.PerlPackage#getPFeatureCall()
 * @model
 * @generated
 */
public interface PFeatureCall extends PExpression
{
  /**
   * Returns the value of the '<em><b>Feature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' attribute.
   * @see #setFeature(String)
   * @see org.epic.perl.perl.PerlPackage#getPFeatureCall_Feature()
   * @model
   * @generated
   */
  String getFeature();

  /**
   * Sets the value of the '{@link org.epic.perl.perl.PFeatureCall#getFeature <em>Feature</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature</em>' attribute.
   * @see #getFeature()
   * @generated
   */
  void setFeature(String value);

  /**
   * Returns the value of the '<em><b>Feature Call Arguments</b></em>' containment reference list.
   * The list contents are of type {@link org.epic.perl.perl.PExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature Call Arguments</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature Call Arguments</em>' containment reference list.
   * @see org.epic.perl.perl.PerlPackage#getPFeatureCall_FeatureCallArguments()
   * @model containment="true"
   * @generated
   */
  EList<PExpression> getFeatureCallArguments();

} // PFeatureCall
