/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pod Token</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.epic.perl.perl.PerlPackage#getPodToken()
 * @model
 * @generated
 */
public interface PodToken extends Token
{
} // PodToken
