/**
 * generated by Xtext 2.9.1
 */
package org.epic.perl.perl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PReturn Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.epic.perl.perl.PReturnExpression#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.epic.perl.perl.PerlPackage#getPReturnExpression()
 * @model
 * @generated
 */
public interface PReturnExpression extends PExpression
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(PExpression)
   * @see org.epic.perl.perl.PerlPackage#getPReturnExpression_Expression()
   * @model containment="true"
   * @generated
   */
  PExpression getExpression();

  /**
   * Sets the value of the '{@link org.epic.perl.perl.PReturnExpression#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(PExpression value);

} // PReturnExpression
