/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.epic.perl.perl.PerlPackage#getStatementNode()
 * @model
 * @generated
 */
public interface StatementNode extends Node
{
} // StatementNode
