/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use Include</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.epic.perl.perl.UseInclude#getPragma <em>Pragma</em>}</li>
 *   <li>{@link org.epic.perl.perl.UseInclude#getPackage <em>Package</em>}</li>
 *   <li>{@link org.epic.perl.perl.UseInclude#getStringArgument <em>String Argument</em>}</li>
 *   <li>{@link org.epic.perl.perl.UseInclude#getQwArgument <em>Qw Argument</em>}</li>
 * </ul>
 *
 * @see org.epic.perl.perl.PerlPackage#getUseInclude()
 * @model
 * @generated
 */
public interface UseInclude extends IncludeStatement
{
  /**
   * Returns the value of the '<em><b>Pragma</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pragma</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pragma</em>' attribute.
   * @see #setPragma(String)
   * @see org.epic.perl.perl.PerlPackage#getUseInclude_Pragma()
   * @model
   * @generated
   */
  String getPragma();

  /**
   * Sets the value of the '{@link org.epic.perl.perl.UseInclude#getPragma <em>Pragma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pragma</em>' attribute.
   * @see #getPragma()
   * @generated
   */
  void setPragma(String value);

  /**
   * Returns the value of the '<em><b>Package</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Package</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package</em>' reference.
   * @see #setPackage(PackageStatement)
   * @see org.epic.perl.perl.PerlPackage#getUseInclude_Package()
   * @model
   * @generated
   */
  PackageStatement getPackage();

  /**
   * Sets the value of the '{@link org.epic.perl.perl.UseInclude#getPackage <em>Package</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Package</em>' reference.
   * @see #getPackage()
   * @generated
   */
  void setPackage(PackageStatement value);

  /**
   * Returns the value of the '<em><b>String Argument</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String Argument</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Argument</em>' containment reference.
   * @see #setStringArgument(QuoteToken)
   * @see org.epic.perl.perl.PerlPackage#getUseInclude_StringArgument()
   * @model containment="true"
   * @generated
   */
  QuoteToken getStringArgument();

  /**
   * Sets the value of the '{@link org.epic.perl.perl.UseInclude#getStringArgument <em>String Argument</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Argument</em>' containment reference.
   * @see #getStringArgument()
   * @generated
   */
  void setStringArgument(QuoteToken value);

  /**
   * Returns the value of the '<em><b>Qw Argument</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Qw Argument</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qw Argument</em>' attribute.
   * @see #setQwArgument(String)
   * @see org.epic.perl.perl.PerlPackage#getUseInclude_QwArgument()
   * @model
   * @generated
   */
  String getQwArgument();

  /**
   * Sets the value of the '{@link org.epic.perl.perl.UseInclude#getQwArgument <em>Qw Argument</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qw Argument</em>' attribute.
   * @see #getQwArgument()
   * @generated
   */
  void setQwArgument(String value);

} // UseInclude
