/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl.impl;

import org.eclipse.emf.ecore.EClass;

import org.epic.perl.perl.EndToken;
import org.epic.perl.perl.PerlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>End Token</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EndTokenImpl extends TokenImpl implements EndToken
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EndTokenImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerlPackage.Literals.END_TOKEN;
  }

} //EndTokenImpl
