/**
 * generated by Xtext 2.9.1
 */
package org.epic.perl.perl.impl;

import org.eclipse.emf.ecore.EClass;

import org.epic.perl.perl.PNullLiteral;
import org.epic.perl.perl.PerlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PNull Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PNullLiteralImpl extends PExpressionImpl implements PNullLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PNullLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerlPackage.Literals.PNULL_LITERAL;
  }

} //PNullLiteralImpl
