/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl.impl;

import org.eclipse.emf.ecore.EClass;

import org.epic.perl.perl.PerlPackage;
import org.epic.perl.perl.PodToken;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pod Token</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PodTokenImpl extends TokenImpl implements PodToken
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PodTokenImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerlPackage.Literals.POD_TOKEN;
  }

} //PodTokenImpl
