/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl.impl;

import org.eclipse.emf.ecore.EClass;

import org.epic.perl.perl.PerlPackage;
import org.epic.perl.perl.RegexpQuoteLikeToken;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Regexp Quote Like Token</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RegexpQuoteLikeTokenImpl extends QuoteLikeTokenImpl implements RegexpQuoteLikeToken
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RegexpQuoteLikeTokenImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerlPackage.Literals.REGEXP_QUOTE_LIKE_TOKEN;
  }

} //RegexpQuoteLikeTokenImpl
