/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl.impl;

import org.eclipse.emf.ecore.EClass;

import org.epic.perl.perl.PerlPackage;
import org.epic.perl.perl.RequireInclude;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Require Include</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RequireIncludeImpl extends IncludeStatementImpl implements RequireInclude
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RequireIncludeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerlPackage.Literals.REQUIRE_INCLUDE;
  }

} //RequireIncludeImpl
