/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.epic.perl.perl.PackageStatement;
import org.epic.perl.perl.PerlPackage;
import org.epic.perl.perl.QuoteToken;
import org.epic.perl.perl.UseInclude;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Use Include</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.epic.perl.perl.impl.UseIncludeImpl#getPragma <em>Pragma</em>}</li>
 *   <li>{@link org.epic.perl.perl.impl.UseIncludeImpl#getPackage <em>Package</em>}</li>
 *   <li>{@link org.epic.perl.perl.impl.UseIncludeImpl#getStringArgument <em>String Argument</em>}</li>
 *   <li>{@link org.epic.perl.perl.impl.UseIncludeImpl#getQwArgument <em>Qw Argument</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UseIncludeImpl extends IncludeStatementImpl implements UseInclude
{
  /**
   * The default value of the '{@link #getPragma() <em>Pragma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPragma()
   * @generated
   * @ordered
   */
  protected static final String PRAGMA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPragma() <em>Pragma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPragma()
   * @generated
   * @ordered
   */
  protected String pragma = PRAGMA_EDEFAULT;

  /**
   * The cached value of the '{@link #getPackage() <em>Package</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPackage()
   * @generated
   * @ordered
   */
  protected PackageStatement package_;

  /**
   * The cached value of the '{@link #getStringArgument() <em>String Argument</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringArgument()
   * @generated
   * @ordered
   */
  protected QuoteToken stringArgument;

  /**
   * The default value of the '{@link #getQwArgument() <em>Qw Argument</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQwArgument()
   * @generated
   * @ordered
   */
  protected static final String QW_ARGUMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getQwArgument() <em>Qw Argument</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQwArgument()
   * @generated
   * @ordered
   */
  protected String qwArgument = QW_ARGUMENT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UseIncludeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerlPackage.Literals.USE_INCLUDE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPragma()
  {
    return pragma;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPragma(String newPragma)
  {
    String oldPragma = pragma;
    pragma = newPragma;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerlPackage.USE_INCLUDE__PRAGMA, oldPragma, pragma));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PackageStatement getPackage()
  {
    if (package_ != null && package_.eIsProxy())
    {
      InternalEObject oldPackage = (InternalEObject)package_;
      package_ = (PackageStatement)eResolveProxy(oldPackage);
      if (package_ != oldPackage)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PerlPackage.USE_INCLUDE__PACKAGE, oldPackage, package_));
      }
    }
    return package_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PackageStatement basicGetPackage()
  {
    return package_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPackage(PackageStatement newPackage)
  {
    PackageStatement oldPackage = package_;
    package_ = newPackage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerlPackage.USE_INCLUDE__PACKAGE, oldPackage, package_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public QuoteToken getStringArgument()
  {
    return stringArgument;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStringArgument(QuoteToken newStringArgument, NotificationChain msgs)
  {
    QuoteToken oldStringArgument = stringArgument;
    stringArgument = newStringArgument;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PerlPackage.USE_INCLUDE__STRING_ARGUMENT, oldStringArgument, newStringArgument);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStringArgument(QuoteToken newStringArgument)
  {
    if (newStringArgument != stringArgument)
    {
      NotificationChain msgs = null;
      if (stringArgument != null)
        msgs = ((InternalEObject)stringArgument).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PerlPackage.USE_INCLUDE__STRING_ARGUMENT, null, msgs);
      if (newStringArgument != null)
        msgs = ((InternalEObject)newStringArgument).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PerlPackage.USE_INCLUDE__STRING_ARGUMENT, null, msgs);
      msgs = basicSetStringArgument(newStringArgument, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerlPackage.USE_INCLUDE__STRING_ARGUMENT, newStringArgument, newStringArgument));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getQwArgument()
  {
    return qwArgument;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setQwArgument(String newQwArgument)
  {
    String oldQwArgument = qwArgument;
    qwArgument = newQwArgument;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerlPackage.USE_INCLUDE__QW_ARGUMENT, oldQwArgument, qwArgument));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PerlPackage.USE_INCLUDE__STRING_ARGUMENT:
        return basicSetStringArgument(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PerlPackage.USE_INCLUDE__PRAGMA:
        return getPragma();
      case PerlPackage.USE_INCLUDE__PACKAGE:
        if (resolve) return getPackage();
        return basicGetPackage();
      case PerlPackage.USE_INCLUDE__STRING_ARGUMENT:
        return getStringArgument();
      case PerlPackage.USE_INCLUDE__QW_ARGUMENT:
        return getQwArgument();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PerlPackage.USE_INCLUDE__PRAGMA:
        setPragma((String)newValue);
        return;
      case PerlPackage.USE_INCLUDE__PACKAGE:
        setPackage((PackageStatement)newValue);
        return;
      case PerlPackage.USE_INCLUDE__STRING_ARGUMENT:
        setStringArgument((QuoteToken)newValue);
        return;
      case PerlPackage.USE_INCLUDE__QW_ARGUMENT:
        setQwArgument((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PerlPackage.USE_INCLUDE__PRAGMA:
        setPragma(PRAGMA_EDEFAULT);
        return;
      case PerlPackage.USE_INCLUDE__PACKAGE:
        setPackage((PackageStatement)null);
        return;
      case PerlPackage.USE_INCLUDE__STRING_ARGUMENT:
        setStringArgument((QuoteToken)null);
        return;
      case PerlPackage.USE_INCLUDE__QW_ARGUMENT:
        setQwArgument(QW_ARGUMENT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PerlPackage.USE_INCLUDE__PRAGMA:
        return PRAGMA_EDEFAULT == null ? pragma != null : !PRAGMA_EDEFAULT.equals(pragma);
      case PerlPackage.USE_INCLUDE__PACKAGE:
        return package_ != null;
      case PerlPackage.USE_INCLUDE__STRING_ARGUMENT:
        return stringArgument != null;
      case PerlPackage.USE_INCLUDE__QW_ARGUMENT:
        return QW_ARGUMENT_EDEFAULT == null ? qwArgument != null : !QW_ARGUMENT_EDEFAULT.equals(qwArgument);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (pragma: ");
    result.append(pragma);
    result.append(", qwArgument: ");
    result.append(qwArgument);
    result.append(')');
    return result.toString();
  }

} //UseIncludeImpl
