/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.epic.perl.perl.impl;

import org.eclipse.emf.ecore.EClass;

import org.epic.perl.perl.PerlPackage;
import org.epic.perl.perl.VersionToken;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Version Token</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VersionTokenImpl extends TokenImpl implements VersionToken
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VersionTokenImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerlPackage.Literals.VERSION_TOKEN;
  }

} //VersionTokenImpl
