/**
 * generated by Xtext 2.9.1
 */
package org.epic.perl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.epic.perl.ui.AbstractPerlUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PerlUiModule extends AbstractPerlUiModule {
  public PerlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
